[files]
input_dir = "typ"
output_dir = "dist"
public_dir = "public"
include = ["**/*.typ"]  # optional; defaults to all files in input_dir
exclude = ["_template/*.typ"]   # optional; exclude has priority over include
# the above is the equivalent of the corresponding CLI flags

[site]
domain = "https://hanwenguo.github.io" # the domain of the site; used for generating absolute URLs
root_dir = "/weibian/" # the root directory of the site; for example, if the site is hosted at example.com/notes/, set root_dir = "/notes/"; if hosted at the root domain, set root_dir = "/"
trailing_slash = true # if true, the final URL of each note will have a trailing slash
